AWSTemplateFormatVersion: 2010-09-09

Description: 'EKS cluster for New Relic Guestbook'

Parameters:
  Prefix:
    Description: When sharing 1 AWS account with other people, set a prefix to avoid naming conflicts. Leave empty if this is your personal AWS account. The prefix will be added to all created resources. Use the same prefix as earlier.
    Type: String
    Default: ''
  ClusterName:
    Type: String
    Default: NewRelicGuestbookCluster

Resources:
  EKSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
      - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
      RoleName: !Sub '${Prefix}eks-role'
  
  # Networking for EKS
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: !Sub '${Prefix}NewRelicGuestbookVPC'
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:
        Ref: InternetGateway
      VpcId:
        Ref: VPC
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
      - Key: Name
        Value: Public Subnets
      - Key: Network
        Value: Public
  Route:
    DependsOn: VPCGatewayAttachment
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
  Subnet01:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
        - '0'
        - Fn::GetAZs:
            Ref: AWS::Region
      CidrBlock: 192.168.64.0/18
      VpcId:
        Ref: VPC
      Tags:
      - Key: Name
        Value: !Sub '${Prefix}NewRelicGuestbookSubnet01'
  Subnet02:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
        - '1'
        - Fn::GetAZs:
            Ref: AWS::Region
      CidrBlock: 192.168.128.0/18
      VpcId:
        Ref: VPC
      Tags:
      - Key: Name
        Value: !Sub '${Prefix}NewRelicGuestbookSubnet02'
  Subnet01RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: Subnet01
      RouteTableId:
        Ref: RouteTable
  Subnet02RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: Subnet02
      RouteTableId:
        Ref: RouteTable
  ControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${Prefix}NewRelicGuestbookControlPlaneSecurityGroup'
      GroupDescription: Cluster communication with worker nodes
      VpcId:
        Ref: VPC

  # EKS
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Sub '${Prefix}${ClusterName}'
      Version: '1.11'
      RoleArn:
        !Sub arn:aws:iam::${AWS::AccountId}:role/${Prefix}eks-role
      ResourcesVpcConfig:
        SecurityGroupIds:
        - Ref: ControlPlaneSecurityGroup
        SubnetIds: [{'Ref': 'Subnet01'}, {'Ref': 'Subnet02'}]
