AWSTemplateFormatVersion: 2010-09-09

Description: 'Lambda + SQS for New Relic Guestbook'

Parameters:
  NewRelicAccountId:
    Description: Your New Relic Account ID
    Type: String
  Prefix:
    Description: When sharing 1 AWS account with other people, set a prefix to avoid naming conflicts. Leave empty if this is your personal AWS account. The prefix will be added to all created resources.
    Type: String
    Default: ''

Resources:
  # Roles
  LambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${Prefix}role-lambda'
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess
      Path: /

  # DynamoDB Table
  MessagesTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub '${Prefix}GUESTBOOK_MESSAGES'
      AttributeDefinitions:
        - AttributeName: CHANNEL
          AttributeType: S
        - AttributeName: TIMESTAMP
          AttributeType: S
      KeySchema:
        - AttributeName: CHANNEL
          KeyType: HASH
        - AttributeName: TIMESTAMP
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'

  # SQS queues
  FrontendQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: !Sub '${Prefix}guestbook-frontend'
      DelaySeconds: '0'
      MaximumMessageSize: '262144'
      MessageRetentionPeriod: '345600'
      ReceiveMessageWaitTimeSeconds: '0'
      VisibilityTimeout: '30'
  ParserQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: !Sub '${Prefix}guestbook-parser'
      DelaySeconds: '0'
      MaximumMessageSize: '262144'
      MessageRetentionPeriod: '345600'
      ReceiveMessageWaitTimeSeconds: '0'
      VisibilityTimeout: '30'

  # Lambda functions
  ParserFunction:
    Type: 'AWS::Lambda::Function'
    Properties: 
      Code: 
        S3Bucket: 'newrelic-lambda-guestbook'
        S3Key: 'parser.zip'
      FunctionName: !Sub '${Prefix}ParserFunction'
      Handler: 'index.handler'
      MemorySize: 512
      Role:
        Fn::GetAtt:
          - LambdaRole
          - Arn
      Runtime: 'nodejs8.10'
      Environment:
        Variables:
          NEW_RELIC_FEATURE_FLAG_SERVERLESS_MODE: true
          NEW_RELIC_NO_CONFIG_FILE: true
          NEW_RELIC_APP_NAME: !Sub '${Prefix}ParserFunction'
          NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: true
          NEW_RELIC_ACCOUNT_ID: !Ref NewRelicAccountId
          NEW_RELIC_PRIMARY_APPLICATION_ID: !Ref NewRelicAccountId
          NEW_RELIC_TRUSTED_ACCOUNT_KEY: !Ref NewRelicAccountId
          WORKSHOP_PREFIX: !Ref Prefix
  WorkerFunction:
    Type: 'AWS::Lambda::Function'
    Properties: 
      Code: 
        S3Bucket: 'newrelic-lambda-guestbook'
        S3Key: 'worker.zip'
      FunctionName: !Sub '${Prefix}WorkerFunction'
      Handler: 'index.handler'
      MemorySize: 512
      Role:
        Fn::GetAtt:
          - LambdaRole
          - Arn
      Runtime: 'nodejs8.10'
      Environment:
        Variables:
          NEW_RELIC_FEATURE_FLAG_SERVERLESS_MODE: true
          NEW_RELIC_NO_CONFIG_FILE: true
          NEW_RELIC_APP_NAME: !Sub '${Prefix}WorkerFunction'
          NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: true
          NEW_RELIC_ACCOUNT_ID: !Ref NewRelicAccountId
          NEW_RELIC_PRIMARY_APPLICATION_ID: !Ref NewRelicAccountId
          NEW_RELIC_TRUSTED_ACCOUNT_KEY: !Ref NewRelicAccountId
          WORKSHOP_PREFIX: !Ref Prefix

  # SQS - Lambda mapping
  FrontendQueueToParserMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !GetAtt FrontendQueue.Arn
      FunctionName: !GetAtt ParserFunction.Arn
  ParserQueueToWorkerMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !GetAtt ParserQueue.Arn
      FunctionName: !GetAtt WorkerFunction.Arn
